language: elixir

addons:
  apt:
    packages:
      - autoconf
      - automake
      - gettext
      - openssl

elixir:
  - 1.7.4
otp_release:
  - 21.1

matrix:
  include:
    - os: linux
      sudo: false
      before_install:
        - curl https://sh.rustup.rs | sh -s -- -y
        - export PATH="$HOME/.cargo/bin:$PATH"
      script:
        - mix test
        - mix credo --strict
        - mix dialyzer --bail
      after_script:
        - MIX_ENV=docs mix deps.get
        - MIX_ENV=docs mix inch.report
    - os: osx
      language: generic
      before_install:
        - curl https://sh.rustup.rs | sh -s -- -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - brew update
        - brew install elixir
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
      script:
        - mix test
        - mix credo --strict
        - mix dialyzer --bail

notifications:
  email:
    on_success: change
    on_failure: change
