[package]
name = "exopenssl"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exopenssl"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.21.1"
rustler_codegen = "0.21.1"
lazy_static = "1.2"
openssl = "0.10.33"